language: node_js
node_js:
- "0.10"

script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/<your name>/<your repo>.git
  - secure: "VAHc2FNLH4yBIqipz0/46Jf/IeX8oh27I6iNVR3bGjIk3ynHEpzdMCLyMBD149uh4o7zZArt22+UTh6tw3BFS/K0YplLqX6wCmyxdflmM360dGj1i2+muKQeDO31ZHVs9qxSVbUGIFTXDV36/Pv79AIy/Fl2ZWd1KcOS4GygcwDM6+lN2zgEY3P0XHJRXPtQipbjpHhU3rXBA6pkugLjvpp7wjnsfkqErB77fybeTncqOuku6if4JYV0s00manI8DyeTajN8dPiVOKpA1YnNvs7jl+hxncMIsucGsDmjFeNjjf8y4Nr5fQJuFsxnpjP/S39AyNgvTu2lt1OUvxfd0baNSTtQe64nFp4BIZA3Ftl2af0tKBpnzEGgx+uhkuSCq2BZcPk/VqjTKJfgbffb9hFYJtimU3ySihaYIVwQZsWpbwMuShNknF+mQ54+y8fgeeQwSbdtUooIDSoqpGGfn3AXk6V0hXxM1dwpzpanVSqvpDxYRzJAy5c0UuNr4yKVzHEo7JAx5iRBQCVjGlyNsArKo8E8i/7FqaAvcGS8UxUBY54bfe3vdN40dtKNfAMpI989ipR35TV0WqYcpJBVlcvIDiRE2kXIlz6TD5V6vqW3xzvlvalLqVx+ecW4dT4SP+sdLtk5nZ5ijJJJO5sxTBcsfCsaB1R1Z0jPa3OPmwM="