language: node_js
node_js:
- "0.10"

script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/liudonghua123/xiaozizi_blog.git
  - secure: "UndjpwEvInPfk9yaH1WcU20/PqdfjICXl/dPHk6fdSxcWDM9O8fiPV/36hvq0C6hABu/mnT3T1DVMhzy3G71b+/CVRgQMMx02PwACCCFTQ4X/CnOs8NgR7/OQBt+tFGKvyeE71OJo9Pu61f9Zz9ypzVqIVEyXp6BBoZPOe5eItA0Qp3j3FVjjrgpmUVLWr0Rx2pjLik45db1zd/5apJlForMXC+D+kqB3/09QX8utDkW6xw7KwNL+S4vLT9rNY5RSFUfhlVl15jCvqJTAUks4RJl/LFwsUoqyHtAz64bcVJVQEk8kawji7mx3SQCCItZqlGSflQaXYHE4TIaiZa9olDpv3KE+AKRGiJZFKgkDIMojePaDQ1x9XZ7dCLyCuJMCHOnhCTfu+CstEpHvt3WZj6UuX4Ljwb27WPCtbYkD3qDI/jtGiZVK4dRLICSoYfJh/+1A/lfd8T6l3YAQRPf7U1ogMRHj6AIauBDMk4YIElJmAitOb9dxVEH6MCf15Da39PAprs8LFRJMmeF1BysxiehKK15haqGh9NpH+4kjUv/FaZELturalqo/+5JhGi62+Mcu3XUgWqIf8m/C77JM71k124VDtM9t06FPnU1PFSWwHqi437DmbMSOroi1Sgki9el428DkekMpbcUJvB5rAEmMLTTQXaYqWnXIM1Jd8U="
