language: node_js
node_js:
- "0.10"
- "6"
- "8"

script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/liudonghua123/xiaozizi_blog.git
  - secure: "D40PA0mTsygVuJu0Udzp5b2N8BT+iNTB1syYILokYe6LOYTelYrza+qVH1L7rmhjsrZYcmcA3l3O5HPnxTEq15cqDB29z8xz42lnGeho4c/L9P//m4ZT4NmF/3KPhh88xrIBtwE4axJZEp2OvYTHy6UyaYkHuwDSMNaC6Ro6U3DvI1jkM0UEGGon+0zMyzkNzGZvZjIAjSKrqRp734Xubqhzm9RdTjILGLmb5EEvRJ+sw0mN+X6gotoQddIDVFRduTK+QxdH99dawJBNLXT2QIUEzajHQK8QhwOa7mQUoqs5egVcW/y4EEUyxk2uIyBxYCXVhVBugvN0P256Q9FmbL4YH1MImDNTf7ZyXBMm5/xKbil6+BW/4VU64b2gtQgNYbgV4YqoXeHERAyBKXM0aaEGOE/wu1GKW6XoHmxxDHr8XBxhjIa6/9N0VY9ysvzYB9QgaXKT0xiujPf49IPpOqiXYVc5EgHS5xcauchTc7cvoGQxBc97Iq91vZBp29FouO3ZmQKGIVCC6nXOXOlT6d1iCnVDg2oip0cDNCn6CnhzzBlRdNpmpTZhmjRLnR8pAWV1uW55WdCiGSTd79NpTrjB9bO3VJHpsVip3OlIGAudhvC1CMw7gbEPlMhecIN4gcyp0Y+Gb1TCGrdANy+tKXbSMlBoHPZlyEStKVo35KA="
